import os
from typing import Dict, Any, List
from unity_modules.map import Map
from unity_modules.tools import *
from agents_modules.agent import AgentManager
from config.logger_config import setup_logger
from config.meta_manager import MetaManager
from config.common_method import advance_time_by_15_minutes
from unity_modules.path_planner import PathPlanner
from concurrent.futures import ThreadPoolExecutor, as_completed
from API.request import UnityRequest
import json

logger = setup_logger('World')


class WorldState:
    def __init__(self, map_data: Dict, unity_request):
        self.town_map = Map(map_data)
        self.unity_request: UnityRequest = unity_request
        # self.agent_manager = AgentManager()
        self.meta_manager = MetaManager()
        self.path_planner = PathPlanner(self.town_map)
        self.global_time = self.meta_manager.get_start_datetime()
        # 创建线程池
        self.thread_pool = ThreadPoolExecutor(max_workers=10)


    def update_status(self, npc_positions: Dict[str, Dict[str, int]]) -> None:
        """
        更新Agent在地图上的位置
        """
        # 清除旧的NPC位置
        self._clear_npc_positions()
        # 更新新的位置
        for npc_name, pos in npc_positions.items():
            # 更新地图上的位置
            self.map.add_npc_to_tile(npc_name, (pos['x'], pos['y']))
            
            # 更新Agent管理器中的位置，考虑需要将当前spawn信息和地图信息同步 保留一处维护
            # 暂时预留这个逻辑，
            # 1， 地图信息需要同步到agent的spawn信息 ✅ or
            # 2， agent的spawn信息需要同步到地图信息
            if npc_name in self.agent_manager.agents:
                self.agent_manager.agents[npc_name].short_memory.current_status['spawn'] = pos
                self.agent_manager.agents[npc_name].short_memory.current_status['next_spawn'] = pos
                self.agent_manager.write_agent_status(npc_name, self.agent_manager.agents[npc_name].short_memory.current_status)


    def update_agent_positions(self, npc_positions: Dict[str, Dict[str, int]]) -> None:
        """
        Updates the positions of NPC agents on the map.

        Args:
            npc_positions (Dict[str, Dict[str, int]]): A dictionary mapping NPC names to their positions and directions.
        """
        for npc_name, pos in npc_positions.items():
            if not all(k in pos for k in ('x', 'y', 'direction')):
                raise ValueError(f"Invalid position data for {npc_name}: {pos}")

            if npc_name == "Zhang San":
                path = self.path_planner.create_path(
                    (pos['x'], pos['y']), (94, 74), pos['direction']
                )

                logger.debug(pos)
                logger.debug(path)
                #logger.debug(path[0])

                if len(path) > 0:
                    self.unity_request.npc_navigate(json.dumps({
                        'npc_name': npc_name, 'speed': 2, 'direction': path[1]
                    }))
