#Elolving Agents: Each time a conversation occurs, the agent reviews a summary of what was previously discussed with the current interlocutor. It then determines a “further” new topic based on the previously discussed topics and discusses around this new topic. This mechanism of dialogue enhances the generation of inspiration and perspectives. For example, Isabella and Sofia's discussion deepened from self-development and social needs to specific ways to maintain creativity and mental health under social pressure, a procedure illustrated in Figure 5. This mechanism mirrors real-world communication, where familiarity and deeper discussions lead to increasingly stimulating and detailed insights into specific topics. Abstract agent relationships: Evolving Agents does not use parameters or specific categories to describe the relationships between agents and others. We found that doing so leads to over-predetermination of interactions with specific agents. We allow the large-scale language model to select a preferred conversational partner based on the agent's interaction memory. At the same time, we require the agent to provide reasons for its choice. This approach leads to more rational and intriguing social choices, allowing agents to openly choose conversation partners and gain diverse perspectives on the dilemma. For example, Isabella, who is balancing external expectations with personal aspirations, might focus on issues such as personal dreams and social responsibility with Sophia, a literary scholar interested in social insights, as shown in Figure 6, or on the balance between personal pursuits and intimate relationships with Ira, a romantic film director The process might be. We believe that this process will help the agent pursue more possibilities in the personality evolution process.

#However, in our system, the information filtered through the Memory module remains a huge amount of fragmented data, making it difficult for the agent to integrate them for holistic thinking. Therefore, we designed the Insight sub-module within the Cognition module to be able to simulate this holistic thinking process. Furthermore, we aim for Insight to reflect the diversity of individual cognitive processes. To this end, we have made it possible for Insight to refer to the complete personality structure and to summarize and reflect all the events and long-term memories of a day. For example, on Day 1, Benjamin realizes that to become a well-rounded person, he needs not only technological breakthroughs, but also humanitarian care and improved social skills; on Day 2, Benjamin sees the possibility of combining technology and the humanities and begins to incorporate a humanitarian perspective into his technological explorations; on Day 3, Benjamin realizes that he needs to be a better person and that he must be able to work with others, seek a harmonious balance between the two. The procedure is shown in Figure 11.3.2.4. Chain-like update process: the CharacterGrowth module simulates the update of an agent's personality, translating its daily evolution into a comprehensive description that is updated in the agent's Character Structure. This structure does not contain complex algorithmic logic, but requires high accuracy through rapid engineering to accurately describe personality changes. We designed the Character Growth process in a chain-like pattern after considering the interrelationships within the Character Structure and dividing it into four successive sub-processes based on the dimensions of the Character Structure, excluding basic information: State Modification , Feature Modification, Discrepancy Modification, and Preference Modification. In designing the specific prompts, the dimensions of the character structure are maintained, and new personality information based on the agent's current state is continuously summarized and filled into the corresponding dimensions. In continually assessing subsequent growth, this growth mechanism provided a traceable and observable description of personality changes.
# For example, compared to Benjamin on Day 1, when he was immersed in technology, his personality now includes a perception that life involves more than work and academics, and he is more focused on maintaining his health and well-being. This change was influenced by Zoe's encouragement of a healthy lifestyle in their conversation, as shown in Figure 12, which highlights the transformation in Benjamin's personality. Similarly, Isabella's interaction with Sofia and her solitary introspection in the square transforms her from a conformist personality to one that is more free and genuine.

from prompt.llm_command_list import *
from agents_modules.personality.emotion import get_complex_mood
def reflection(agent, action, description):
    needs = agent.short_memory.basic_needs
    if action == 'move':
        needs['energy'] -= 1
    else:
        needs = gpt_analyze_needs( agent.name, agent.formed_profile, get_complex_mood(agent.short_memory.emotion_memory[-1]), action, description, needs)
    agent.short_memory.basic_needs = needs.get('new_basic_needs')
    agent.short_memory.emotion_memory.append(needs.get('new_emotion'))
    return needs
    
def cognition(self):
    self.agent = 0
    self.knowledge_base = {}
    self.decision_history = []
    
    learnings = gpt_analyze_memory(self.basic_info['goals'], self.short_memory.recent_events)
    return learnings

def growth(self):
    pass
    